### ISSUE TITLE
Error: Cannot redefine property: $ctrl

### ISSUE THREAD

**Issue by zachhardesty7** [anton-lunev/angular-state-inspector#12]
Like #7, I receive the above error. Whatever component has focus when the page (re)loads will correctly display the information. Clicking any other element in inspector breaks it. The `$state` console shortcut appears to work fine. `$ctrl` returns null.

Some info: this is a large web app running Angular and React instances. Let me know if there's any other info I could quickly get you that would help. I'm not very familiar with Angular so I'm not sure where or what would help.

**Comment by rogerfar** [comment]
This has started happening for us too in the Chrome 93.

**Comment by anton-lunev** [comment]
Hi @rogerfar, 
Could you specify any project details that can possibly affect it? Do you also run react and angular together?
It would be ideal to create a minimal reproducible demo in stackblitz or any other online editor, so that I could fix it asap.

**Comment by rogerfar** [comment]
Hi @anton-lunev, it's a private internal project, but the problem also occurs right on the login page: https://dev-test.fieldcap.ca/#/Login

This is tested on Chrome 93.0.4577.42 (beta).

We only use AngularJS, not React.

**Comment by anton-lunev** [comment]
@rogerfar Do you use components in your project? 
Here is the main difference between $state and $ctrl
 - $state shows any angular related metadata that selected dom element contains
 - As for $ctrl, extension gets $state of selected element and simply searches .$ctrl property up through the all $parent scopes. $ctrl is a default alias(controllerAs) for angularjs component controllers. So if you don't use components style or manually specify $ctrl alias, it's not supposed to work. Please see related docs: https://docs.angularjs.org/guide/component

**Comment by anton-lunev** [comment]
Added info message in case $ctrl is not available in selected scope.
