### ISSUE TITLE
In production release i not see the state

### ISSUE THREAD

**Issue by mikyweb** [anton-lunev/angular-state-inspector#19]
Hi, I made an app with Angular 11.0.6 and I don't see the state in production. Can you tell me why and how I could enable the extension in production? Thanks

**Comment by anton-lunev** [comment]
Don't think it's possible for now, this is rather limitation of angular that removes developmnet metadata from production build for better performance and smaller bundle size. Basically even official https://github.com/rangle/angular-devtools does not support production builds yet.
