### ISSUE TITLE
Link to GitHub on AMO

### ISSUE THREAD

**Issue by rklec** [anton-lunev/angular-state-inspector#21]
On your add-on listing in https://addons.mozilla.org/firefox/addon/angular-state-inspector you have no link to GitHub so it's hard to know where to report bugs.

A link,m you can e.g. provide on as an "support channel" or official homepage  (which would appear in the left panel)would likely be very helpful.

**Comment by anton-lunev** [comment]
This link is for another extension with the same name.
This extension you can find here: https://addons.mozilla.org/en-US/firefox/addon/angular_state_inspector/
And it also has all the links ;)
