### ISSUE TITLE
Causes "Uncaught TypeError: ng.probe is not a function"

### ISSUE THREAD

**Issue by rklec** [anton-lunev/angular-state-inspector#22]
```
Uncaught TypeError: ng.probe is not a function
    isDebugMode ng-validate.js:1
    l ng-validate.js:1
    e ng-validate.js:1
    invoke zone.js:400
    runGuarded zone.js:171
    wrap zone.js:154
    className zone.js:940
    n ng-validate.js:1
    306 ng-validate.js:1
    r ng-validate.js:1
    305 ng-validate.js:1
    r ng-validate.js:1
    <anonymous> ng-validate.js:1
    <anonymous> ng-validate.js:1
```
...which [you clearly use](https://github.com/anton-lunev/angular-state-inspector/search?q=ng.probe).

Should be easily fixable: https://stackoverflow.com/questions/56373044/error-in-console-ng-probe-is-not-a-function
In Ivy you can use `getComponent` instead.

## Versions

add-on v1.5.0
An Angular v13.3.2 app
Firefox 101.0.1
Windows 10

**Comment by anton-lunev** [comment]
Based on other issues from you I assume you're using a different extension with the same name.
Please find my extension here https://addons.mozilla.org/en-US/firefox/addon/angular_state_inspector/
As you can see this extension also uses `getComponent` ([see examples](https://github.com/anton-lunev/angular-state-inspector/search?q=getComponent)), so everything should work.
Feel free to reopen this issue if it throws a similar error.
