### ISSUE TITLE
Hybrid application: broken angular 2+ context

### ISSUE THREAD

**Issue by pichuser** [anton-lunev/angular-state-inspector#3]
Hello! Very nice and usefull extension!
Last version 1.3 stop working as before for hybrid AngularJs|Angular2+ application with downgrade module.
As seen on screenshot check for window.angular go first - and in my hybrid application there is always window.angular... But before the first check was ` if (ng && ng.probe($0))`. May be just change to - 1) angular 2+ ; 2) angular Ivy ; 3) angularJs ?
![2019-06-25_11-05-12](https://user-images.githubusercontent.com/9981930/60076659-2dde8a80-9739-11e9-9ad2-d5ca6a836b01.png)

**Comment by anton-lunev** [comment]
Hi @pichuser. Thanks for catching it. Just published extension with the fix. Good luck with your migration ;)
