### ISSUE TITLE
Chrome Canary

### ISSUE THREAD

**Issue by peteichuk** [anton-lunev/angular-state-inspector#6]
this extension incorrect work in Chrome Canary, but in basic Chrome, it works correctly

**Comment by anton-lunev** [comment]
Hey @peteichuk, I responded to you on extension page. 
At the time you filed this issue it worked inconsistently, chrome extension API seemed broken. I checked it once again today and it seems working as expected. Please update your chrome and try it. I guess you can expect weird bugs in the canary version from time to time.

**Comment by peteichuk** [comment]
> Hey @peteichuk, I responded to you on extension page.
> At the time you filed this issue it worked inconsistently, chrome extension API seemed broken. I checked it once again today and it seems working as expected. Please update your chrome and try it. I guess you can expect weird bugs in the canary version from time to time.

Thanks!
